### ISSUE TITLE
Show average walking speed

### ISSUE THREAD

**Issue by Wall-Dough** [ScienceSquad/Health#15]
_< no comment >_

---
- **Estimated Time:** _4 hours._
- **Prerequisites:** _Sensor Integration._

**Comment by colinrford** [comment]
I would imagine this can be coupled with #24 and #19

**Comment by Wall-Dough** [comment]
Yeah, it probably can. I think I made these separate simply to inflate our user stories.

**Comment by colinrford** [comment]
Use what has been provided by Android already
Perform some easy math
Test

**Comment by colinrford** [comment]
done
