### ISSUE TITLE
Calculate and track length of stride

### ISSUE THREAD

**Issue by Wall-Dough** [ScienceSquad/Health#19]
_< no comment >_

---
- **Estimated Time:** _10 hours._
- **Prerequisites:** _Google Fit API, Unknown?._

**Comment by colinrford** [comment]
Please let me know if my updated time commitment is too much of an exaggeration. I doubled because I figured it's gonna take a bit of time to get acquainted with related API's. Also, I assigned myself to this and moved it to **Sprint 1** because of it's relation to #24 and #15

**Comment by colinrford** [comment]
done
