### ISSUE TITLE
Know how many calories I burned during my route

### ISSUE THREAD

**Issue by brandonschabell** [ScienceSquad/Health#22]
_This module will be able to calculate how many calories are burned during a run/cycle route (and provide live information as well). This information will be calculated using user information (height, weight, age, gender, etc.) and pacing information. This information will need to be displayed live during a workout and be saved following a completed route._

---
- **Estimated Time:** _5 hours._
- **Prerequisites:** _Nutrition Module, Sensor Integration._

**Comment by colinrford** [comment]
See #20 for comment

**Comment by avaidyam** [comment]
Done!
