### ISSUE TITLE
Show and log amount of time spent walking

### ISSUE THREAD

**Issue by Wall-Dough** [ScienceSquad/Health#24]
Stopwatch readily available in pedometer module

---
- **Estimated Time:** _1 hours._
- **Prerequisites:** _Stopwatch UI, Sensor Integration._

**Comment by Wall-Dough** [comment]
Should probably use the [Chronometer class](http://developer.android.com/reference/android/widget/Chronometer.html).

**Comment by avaidyam** [comment]
[Here's a good design for it.](https://developers.google.com/glass/develop/patterns/ongoing-task)

**Comment by colinrford** [comment]
I updated this to include it in **Sprint 1** because of it's relation to #15 and #19

**Comment by colinrford** [comment]
I'm gonna tag this along with #4 too

**Comment by colinrford** [comment]
done'
