### ISSUE TITLE
Create running or cycling routes

### ISSUE THREAD

**Issue by brandonschabell** [ScienceSquad/Health#25]
_Module will be able to design a route that follows roads and paths. The module must be capable of calculating distances and saving route information._

---
- **Estimated Time:** _6 hours._
- **Prerequisites:** _Sensor Integration._

**Comment by MrJohnson** [comment]
Again, I do have some experience with Google Maps on Android, so if you run into trouble I can try to assist.

**Comment by brandonschabell** [comment]
Done!
