### ISSUE TITLE
Catalog all sleep deficits during a week

### ISSUE THREAD

**Issue by avaidyam** [ScienceSquad/Health#32]
A fundamental part of all sleep tracking functions involve receiving accelerometer and microphone data and processing them for meaningful information. The accelerometer would function if the phone is placed next to the user during their nap or sleep, and corresponding microphone data would indicate restless sleep.

This information coupled with the user's biological sleep cycle can explain sleep deficits.

---
- **Estimated Time:** _5 hours._
- **Prerequisites:** _Sensor Integration, Calendar View._

**Comment by colinrford** [comment]
just curious if this was sprint 1 still or sprint 2? @avaidyam

**Comment by avaidyam** [comment]
Sprint 1. @colinrford you underestimate my ability, young padawan. :wink:

**Comment by colinrford** [comment]
Lolol not at all! Looking forward to seeing this in action

**Comment by avaidyam** [comment]
Basically, I'm gonna get rekt tomorrow night. :grinning:

**Comment by colinrford** [comment]
Shall we close? We are so close to filling the green bar!!!

**Comment by avaidyam** [comment]
yes!

On Fri, Mar 4, 2016, 3:32 PM Colin Ford notifications@github.com wrote:

> Shall we close? We are so close to filling the green bar!!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ScienceSquad/Health/issues/32#issuecomment-192456666.
> 
> ## 

## 

Aditya.
