### ISSUE TITLE
Understand if any of a user's prescription or over-the-counter medications will impede their ability to sleep well

### ISSUE THREAD

**Issue by avaidyam** [ScienceSquad/Health#37]
This would require a built-in `Prescriptions` module or similar with a set of medications that the user will be on. In that case, look the medication up in a database like OpenFDA for known sleep-related side effects. This can be displayed to the user as a non-intrusive alert.

---
- **Estimated Time:** _11 hours._
- **Prerequisites:** _Prescriptions Module._

**Comment by colinrford** [comment]
are we planning on doing this in sprint 1 or 2? @Wall-Dough

**Comment by avaidyam** [comment]
@Wall-Dough How is this doing?

**Comment by colinrford** [comment]
done
