### ISSUE TITLE
Soothing sleep sounds, designed to ease the stress from a workday

### ISSUE THREAD

**Issue by avaidyam** [ScienceSquad/Health#38]
Would be simple enough to provide a set of noises as mp3 samples:
- Rain
- Thunder
- Fire
- Wind
- Birds
- Insects

Allow the user to set the volume level and fade in/out period, and save these combinations as presets. Optionally, allow randomizing ("meandering") the different noises.

---
- **Estimated Time:** _1 hour._
- **Prerequisites:** _None._

**Comment by avaidyam** [comment]
Issue update: Acquired 35 MB of nature sounds from ASoftMurmur.

**Comment by avaidyam** [comment]
Issue update: **Operational!**

Currently, meandering is done by default-- a user interface for the sounds should be added to control individual volume levels.

**Comment by colinrford** [comment]
this is done as well!
