### ISSUE TITLE
Intuitive App Navigation

### ISSUE THREAD

**Issue by colinrford** [ScienceSquad/Health#39]
Allow the user to be able to access different aspects of the app with ease (fewer 'taps' ideal).

---
- **Estimated Time:** _4 hours._
- **Prerequisites:** _None._

**Comment by avaidyam** [comment]
Perhaps using a [NavigationView](http://antonioleiva.com/navigation-view/) with several views would be helpful. Each row of the sidebar would be a module; we can use Java reflection to find all subclasses of `Module` and display them automatically too!

This would mean `class Module` would need functions `String title()` and `View view()` at the minimum to auto-hook everything together. If we pull this part off, `Module` code would become MUCH easier!

**Comment by colinrford** [comment]
Become familiar with the NavigationView as well as Material Design 
Create several mockup UI's with Sketch, and learn how to manipulate/create UI through code
Test on each group member's device

**Comment by colinrford** [comment]
I just want to remember this repo later https://github.com/Clans/FloatingActionButton

**Comment by colinrford** [comment]
This is going to take some time since we are going to need to perform a transition to MVVM

**Comment by avaidyam** [comment]
@colinrford Not really, I have great ideas coming up. It will be done in the next few days.

**Comment by colinrford** [comment]
plz shr

**Comment by avaidyam** [comment]
Using the Android `Loader` to connect the `Module` to the View instead of writing my own logic. Then, use the `Intent` system to show new `Module`s or stuff. (Something like `Module.displayModule(Intent)` would do, kinda like `Context.startActivity(Intent)`)

**Comment by colinrford** [comment]
Brilliant!

**Comment by avaidyam** [comment]
@colinrford @Wall-Dough @MrJohnson @Brahmancer @brandonschabell Marking as done, as of today.
