### ISSUE TITLE
Keep count of total steps taken

### ISSUE THREAD

**Issue by Wall-Dough** [ScienceSquad/Health#4]
Pedometer module

---
- **Estimated Time:** _1 hours._
- **Prerequisites:** _Sensor Integration._

**Comment by Brahmancer** [comment]
There's a open-source pedometer that can be used as a possible jump-off point to implementing our own. https://github.com/bagilevi/android-pedometer

**Comment by avaidyam** [comment]
Even better is that we can use [sample code](https://github.com/j4velin/Pedometer) that hooks into the hardware step sensors. Though the code you linked is usable, it's really convoluted and written badly so it wouldn't make sense to integrate it.

**Comment by avaidyam** [comment]
Here's what we'll ultimately need: [`Sensor.TYPE_STEP_COUNTER`](http://developer.android.com/reference/android/hardware/Sensor.html)

**Comment by Brahmancer** [comment]
Needed: 
Working Pedometer to incorporate sensor.

**Comment by avaidyam** [comment]
Done. #65
