### ISSUE TITLE
Health Routine Evaluation

### ISSUE THREAD

**Issue by colinrford** [ScienceSquad/Health#42]
Give user information on how various aspects of their health routine affect their overall health and how various aspects of their health routine affect other specific aspects.

---
- **Estimated Time:** _12 hours._
- **Prerequisites:** _Coupled with #43._

**Comment by avaidyam** [comment]
See #43 for examples.

**Comment by colinrford** [comment]
This encompasses more than just a display/UI, but I don't know how to label it accordingly

**Comment by colinrford** [comment]
This is actually going to take a while because I need to create an overview "module" that is able to talk to all of the modules and their realms, collect relevant data, analyze it and spit out some sort of number or evaluation of the user's overall health

**Comment by avaidyam** [comment]
@colinrford Good approach. I think we should actually move the "number crunching" into the individual module. That is, each module would report their "health coefficient" and the `OverviewModule` would just average it all, and show a little chart, along with suggestions.

To be fair, this is exactly what the **entire** Apple Health and Google Fit app does. We're kinda going above and beyond!

**Comment by colinrford** [comment]
@avaidyam Perhaps, then, included in this task I will work with each module (and that module's respective person) to create these health coefficients

**Comment by avaidyam** [comment]
@colinrford MVP! Sounds like a plan. :)

**Comment by colinrford** [comment]
This is done for sprint 2!
