### ISSUE TITLE
Module UI integration hooks

### ISSUE THREAD

**Issue by avaidyam** [ScienceSquad/Health#45]
There should be a set of UI-related hooks in place for a module to reactively control its UI component.
See [Android's Data Binding library](http://developer.android.com/tools/data-binding/guide.html) as well.

@colinrford 

---
- **Estimated Time:** _12 hours._
- **Prerequisites:** _Module Support._

**Comment by colinrford** [comment]
Just one more!!! @Wall-Dough @avaidyam @Brahmancer @MrJohnson @brandonschabell

**Comment by avaidyam** [comment]
This is what I've been working on this whole time, Colin.... lol :smile:
