### ISSUE TITLE
Database backup support

### ISSUE THREAD

**Issue by avaidyam** [ScienceSquad/Health#47]
Support the [Android BackupAgent API](http://developer.android.com/training/backup/backupapi.html).

---
- **Estimated Time:** _1 hour._
- **Prerequisites:** _Realm Integration._

Todo: 
Use [Android BackupAgent API](http://developer.android.com/training/backup/backupapi.html) to find a way to store backups of the realm file.

**Comment by Brahmancer** [comment]
Would the individual modules have their own backup or would we just have a massive backup for the entire app? I would think it worthwhile to entertain the idea of having both options available to the user.

**Comment by avaidyam** [comment]
To make it simple for the module context binding, the **entire** set of all Realms will be backed up. This is only for the currently logged in Google account, and of course it'll be possible to reset all things in a single module's Realm later.

**Comment by avaidyam** [comment]
This is one of those things where we want it to be a free lunch with little thinking to do. :shipit:

**Comment by Brahmancer** [comment]
That's cool. Just wanted to be on the same page. I feel like we can add the individual module to the "time permitting" portion of the project however, if the idea is appealing to you. :grin:

**Comment by avaidyam** [comment]
@Brahmancer looks like it's fairly simple:

Add the following to the `<application>` tag in `AndroidManifest.xml`:

``` xml
<application
            android:allowBackup="true"
            android:backupAgent=".BackupAgent"
            android:fullBackupOnly="true"
            android:fullBackupContent="true"
            android:name="com.your.app.here">
            <meta-data
                android:name="com.google.android.backup.api_key"
                android:value="YOUR_API_KEY"/>
</application>
```

And use code something like this for the backup agent:

``` java
public class BackupAgent extends BackupAgentHelper {
    @Override
    public void onCreate() {
        super.onCreate();
        BackupHelper helper = new FileBackupHelper(getApplicationContext(), Realm.getDefaultInstance().getPath());

        addHelper("database", helper);
    }
}
```

Then, when the data is changed, call this:

``` java
BackupManager backups = new BackupManager(getContext());
backups.dataChanged();
```

Not sure how valid this would be though.

**Comment by Brahmancer** [comment]
Would this be corresponding to each database that we have set up or one massive backup?

**Comment by avaidyam** [comment]
Dude, beats me. It's your call if you want it. :)

**Comment by Brahmancer** [comment]
:+1: I'll figure something out :smile:

**Comment by Brahmancer** [comment]
Added in with #55. Grabbed a key from Google and we should be able to use it now.
