### ISSUE TITLE
Stopwatch View

### ISSUE THREAD

**Issue by Wall-Dough** [ScienceSquad/Health#48]
- Count up ([Chronometer](http://developer.android.com/reference/android/widget/Chronometer.html))
- Count down ([CountDownTimer](http://developer.android.com/reference/android/os/CountDownTimer.html))
- Laps
### TO DO:
- Implement Chronometer class as a module
- Use default views for Chronometer
- Attempt to implement a new UI for the Chronometer
- Implement CountDownTimer as a different mode
- Implement laps for Chronometer

---
- **Estimated Time:** _6 hours._
- **Prerequisites:** _None._

**Comment by avaidyam** [comment]
I like this concept:

![](https://d13yacurqjgara.cloudfront.net/users/32512/screenshots/2283280/3222untitled-1.png)

**Comment by Wall-Dough** [comment]
WHOO!
