### ISSUE TITLE
Standard Units API

### ISSUE THREAD

**Issue by avaidyam** [ScienceSquad/Health#49]
There should be a standard measurement `Unit` API with included conversions from different types. It should support both SI and Imperial unit classes. An example is available [here](http://jsr-108.sourceforge.net/javadoc/javax/units/SI.html) (which can possibly be copied as-is).
### TO DO:

Copy and paste code into project
Integrate code into project
See if it works

---
- **Estimated Time:** _0 hours._
- **Prerequisites:** _None._

**Comment by avaidyam** [comment]
@brandonschabell

**Comment by Wall-Dough** [comment]
To DO:
Copy and paste code into project
Integrate code into project
See if it works

**Comment by avaidyam** [comment]
Deferred until necessity arises.
