### ISSUE TITLE
Track Calorie Intake

### ISSUE THREAD

**Issue by Brahmancer** [ScienceSquad/Health#5]
Implement a feature where a user can input their calorie intake for the day. This would come with a creation of a Nutrition Module. 

---
- **Estimated Time:** _4 hours._
- **Prerequisites:** _Nutrition Module._

**Comment by Brahmancer** [comment]
There was alot of pressure being done in Sprint 2. Just trying to alleviate some pressure off that Sprint. If not done during Sprint 1, this should take priority in Sprint 2.

**Comment by avaidyam** [comment]
:+1:

**Comment by Brahmancer** [comment]
Needed: 
Implementing a Nutrition Module w/ database
Basic way of inputing data (with and w/o ui)

**Comment by avaidyam** [comment]
@Brahmancer How is this doing?

**Comment by Brahmancer** [comment]
#64
