### ISSUE TITLE
Digital emergency card that will be displayed during workouts

### ISSUE THREAD

**Issue by Wall-Dough** [ScienceSquad/Health#50]
### TO DO:

Set up class for emergency notifications
Set text of notification, maybe an emergency level
Receive request for notification, send notification

Event for sending notification?

---
- **Estimated Time:** _1 hours._
- **Prerequisites:** _Prescriptions Module._

**Comment by Wall-Dough** [comment]
TO DO:
Set up class for emergency notifications
Set text of notification, maybe an emergency level
Receive request for notification, send notification
- Event for sending notification?

**Comment by MrJohnson** [comment]
This should be implemented so that it is quickly accessible during any physical "activity." The challenge will be to find a way to make it easily accessible and semi-obvious while remaining unobtrusive. I will be working on the exercise logging, so assisting on this issue/feature seems logical.

**Comment by avaidyam** [comment]
A suggestion is to use Android's **Ongoing Notification** with a custom view. 

``` java
Notification note = new NotificationCompat.Builder(getContext())
    .setOngoing(true)
    .setContent(new RemoteView(getPackageName(), R.layout.my_view_layout))
    .build();
```

It's all dusty in the corners of my mind, but it'd be something like that. It might look something like this:
![](http://i.stack.imgur.com/a7XDm.png)

Except, it wouldn't be in the notification ticker at the top -- only visible if you slide down the notification shade.

**Comment by colinrford** [comment]
this is good! you're the best @Wall-Dough!
