### ISSUE TITLE
Prescription alarms

### ISSUE THREAD

**Issue by Wall-Dough** [ScienceSquad/Health#51]
AlarmManager
SystemAlarms

INSPIRATION
SleepCycle
SleepBetter (Runtastic)
### TO DO:

Use AlarmManager/SystemAlarms classes to schedule alarms for prescription refills
Receive request to set alarm

---
- **Estimated Time:** _3 hours._
- **Prerequisites:** _Prescriptions Module._

**Comment by Wall-Dough** [comment]
Use AlarmManager/SystemAlarms classes to schedule alarms for prescription refills
Receive request to set alarm

**Comment by colinrford** [comment]
is this also sprint 1 still @Wall-Dough ?

**Comment by Wall-Dough** [comment]
@colinrford Yep, working on it now!

**Comment by colinrford** [comment]
@Wall-Dough I assume this guy is done too?

**Comment by colinrford** [comment]
this is technically not done! but will be soon
