### ISSUE TITLE
Track my run or cycling route

### ISSUE THREAD

**Issue by brandonschabell** [ScienceSquad/Health#6]
_Import live location data to track user's location, pacing information, distance traveled, etc. This data must be saved following the run/cycle route._

---
- **Estimated Time:** _12 hours._
- **Prerequisites:** _Google Fit API, Google Maps API, Sensor Integration, Geofencing?._

**Comment by MrJohnson** [comment]
Hopefully this Module should be a little more straightforward than some of the others. I do have some experience working with Google Maps in Android, so if you run into trouble I can try to assist. If we are not able to pull tracking data straight from Android, building our own implementation would be pretty straightforward: collect location data ever few seconds, save the Markers in an Array with some sort of timestamp.

**Comment by avaidyam** [comment]
Done!
