### ISSUE TITLE
Barcode Scanner

### ISSUE THREAD

**Issue by Brahmancer** [ScienceSquad/Health#70]
Have functionality where the app can scan barcodes and produce meaningful data from it and show it to the user.  

---
- **Estimated Time:** _9 hours_
- **Prerequisites:** _NutritionModule_ _NutritionViewModel_ _Barcode Scanner API_

**Comment by avaidyam** [comment]
[Use ZXing.](http://stackoverflow.com/questions/2050263/using-zxing-to-create-an-android-barcode-scanning-app)

**Comment by Brahmancer** [comment]
Really good link http://stackoverflow.com/questions/18543668/integrate-zxing-in-android-studio

**Comment by Brahmancer** [comment]
#87
