### ISSUE TITLE
Workout logging

### ISSUE THREAD

**Issue by MrJohnson** [ScienceSquad/Health#8]
Implement a feature that allows a user to enter workout information

---
- **Estimated Time:** _2 hours._
- **Prerequisites:** _None._

**Comment by Wall-Dough** [comment]
We should try to find a way to log for each individual exercise which parts of the body are being worked. Some exercise machines show an image of a human body with different muscle sections, and the muscle sections are highlighted depending on the workout. We should try to implement something like that.

**Comment by colinrford** [comment]
I was thinking more or less the same thing. We should provide a sort of dictionary of common exercises within the app, and easily allow the user to add any additional exercises we don't include. For each exercise we include, we could highlight relevant muscles on a human diagram.

**Comment by avaidyam** [comment]
Are there existing databases out there with workout information?

**Comment by MrJohnson** [comment]
To get started on this, I've been playing around with a few workout logging apps for ideas and inspiration. I will need to create a WorkoutModel Class as well as a WorkoutActivityModel Class (although probably avoid the keyword "Activity" to minimize confusion with "Activities" as they pertain to Android). The main task for me starting will be learning the ins-and-outs of Realm.

**Comment by avaidyam** [comment]
@MrJohnson Don't worry about the `Activity` name -- we're package scoped as `com.sciencesquad.health` for a reason. 😏
